source ~/.alias
source ~/git/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle command-not-found
# antigen bundle composer
antigen bundle docker
antigen bundle docker-compose
antigen bundle git
antigen bundle gulp
antigen bundle heroku
antigen bundle jsontools
antigen bundle pip
# antigen bundle ssh-agent
antigen bundle sublime
antigen bundle svn
antigen bundle wp-cli

# Bundles from the zsh-users repo.
# antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-syntax-highlighting

# Bundles from the unixorn repo.
antigen bundle unixorn/autoupdate-antigen.zshplugin
antigen bundle unixorn/docker-helpers.zshplugin
antigen bundle unixorn/git-extra-commands

# Bundles from other repo.
antigen-bundle Tarrasch/zsh-autoenv

# Load the theme.
antigen bundle nojhan/liquidprompt

# Tell antigen that you're done.
antigen apply
